version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/examples/demo"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/examples/deploy"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/observers/terminal"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "*"
